---
abstract: 'Bitcard authentication for Plack, which I suppose is what you might have guessed from the name'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  HTTP::Request::Common: 0
  URI: 0
  URI::QueryParam: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords: []
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Plack::Middleware::Auth::Bitcard
name: Plack-Middleware-Auth-Bitcard
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  Authen::Bitcard: 0
  JSON: 2.00
  Plack: 1.0000
  perl: 5.8.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Plack-Middleware-Auth-Bitcard
  homepage: https://metacpan.org/release/Plack-Middleware-Auth-Bitcard
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/tobyink/p5-plack-middleware-auth-bitcard
version: 0.001
